### ISSUE TITLE
Check wiki against script

### ISSUE THREAD

**Issue by HedvigS** [grambank/pygrambank#115]
Not urgent, but can we check [sheet.py](https://github.com/grambank/pygrambank/blob/master/src/pygrambank/sheet.py
) and make sure all rules are mentioned in [the corresponding wiki](https://github.com/grambank/grambank/wiki/Automatic-quality-checks). All active rules should be mentioned.

**Comment by johenglisch** [comment]
*Note:* #113 adds [automated tests for all the checks](https://github.com/grambank/pygrambank/blob/4a5c8ca3f355b4d0dac0aaea5f4683e4deb3feb5/tests/test_sheet.py#L42) – we can use those to make sure that all checks are correct (and stay that way).

**Comment by johenglisch** [comment]
Okay, I read through the code and afaict those are the rules missing from the wiki page:

 * If GB256, GB266, and GB273 are all 0, these value rows require a comment.
 * If GB072, GB073, GB074, and GB075 are all 0, GB074 and GB075 require a comment.
 * If GB155 is 1 and GB113 is 0, both value rows require a comment.
 * If GB022 and GB023 are both 0, both value rows require a comment.

And, of course the binarised features:

 * GB024a and GB024b can't both be 0.
 * GB025a and GB025b can't both be 0.
 * GB065a and GB065b can't both be 0.
 * GB130a and GB130b can't both be 0.

I hope I got those right, this onslaught of nondescript feature numbers kinda hurts my brain a little… (<\_<)"

**Comment by HedvigS** [comment]
Thank you @johenglisch ! Updated!
https://github.com/grambank/grambank/wiki/Automatic-quality-checks !
