### ISSUE TITLE
Clean wiki text before adding it to sheet

### ISSUE THREAD

**Issue by xrotwang** [grambank/pygrambank#17]
See https://github.com/glottobank/Grambank/issues/611

**Comment by HedvigS** [comment]
remove line breaks, make all one paragraph (see [Grambank/pull/878](https://github.com/glottobank/Grambank/pull/878))

**Comment by HedvigS** [comment]
The patron peer reviewing is moving forward, we're still a few weeks from finalisation but we're ironing out a lot of issues. There will be some smaller changes to the Feature "question", what is known as "Feature" in the most_updated_sheet. When the wiki text from the summary is being pulled, can we also pull the first section, the feature question, from the wiki articles and populate that into the "Feature"column?
