### ISSUE TITLE
Aggregate coders per datapoint

### ISSUE THREAD

**Issue by xrotwang** [grambank/pygrambank#20]
The current computation of coders per datapoint (https://github.com/glottobank/pygrambank/blob/0254b3b63a0511a2347a0e3aa89d79e4c3112371/src/pygrambank/cldf.py#L171-L176) must be changed such that all associated coders are aggregated. See https://github.com/glottobank/Grambank/pull/631#issuecomment-664982290

**Comment by HedvigS** [comment]
(Can I add to this issue that coders with 0 languages shouldn't be listed [here](https://grambank.clld.org/contributors). There is a case for including some of these in the author list for the ms, Simon and Hannah G for example, but the needn't be listed on the website.)
