### ISSUE TITLE
check on PRs

### ISSUE THREAD

**Issue by HedvigS** [grambank/pygrambank#21]
This is more of a question to @xrotwang than an "issue".

How are you running pygrambank check on new PRs such that you're only evaluating the changes in the branch unique commits? Are you grepping the output afterwards using a list of the files changed from some sort of Git command? Or manually curating a list of the relevant files and filtering for those? 

I understand how to run check on a branch, I'm just looking to effective the output to be more relevant and I suspect you already have a good solution :)

**Comment by HedvigS** [comment]
(Also can I be given more privileges in this repos please I can't assign you Robert.)

**Comment by xrotwang** [comment]
On each submitted sheet, I run:
```
grambank check --filename original_sheets/...
csvstat -t -c Feature_ID,Value original_sheets/...
```
until all issues are ironed out
