### ISSUE TITLE
incorporate Glottolog lookup in check?

### ISSUE THREAD

**Issue by HedvigS** [grambank/pygrambank#23]
I swear we've discussed this before but I can't find where. Incorporating the glottolog look up check (i.e. checking hh.bib and gb.bib links) would be great. I'm going through the warnings now, and some are for fairly recent sheets.

**Comment by xrotwang** [comment]
The glottolog lookup is fairly expensive - a couple of minutes, I think. This makes it unsuitable for a tool like `check` which is used for quickly, iteratively checking the validity of sheets - e.g. when reviewing PRs.

**Comment by HedvigS** [comment]
This glottolog lookup is unearthing a lot of important mistakes, including mislabelling of files. If this check isn't incorporated in pygrambank check, can I please have an easier command than running the full CLDF common then? Because currently that is taking me a while, just to get to the glottolog lookup warnings.

**Comment by HedvigS** [comment]
And I should add, I would run such a check on new incoming sheets because these warnings are really important. I've caught things like people using the wrong glottocode or using a language description which is inappropriate for the coding. These are not things we want to slip through.

**Comment by xrotwang** [comment]
The glottolog reference lookup is by far the most time-consuming part of the `grambank cldf` command. So factoring it out to its own command would not gain us much. I guess, running `grambank cldf` at the very end of validating PRs makes sense, then.

**Comment by HedvigS** [comment]
Okay, I'll keep running cldf then for this. It takes a bit of time for my machine to run through the selecting best sheet, but yes it does seem like the glottolog check up is the most time consuming part of this command.

**Comment by HedvigS** [comment]
For reference, when I run CLDF it takes 24 sec to reach the end of selecting best sheet, 55 sec to get to "loading bib", 1:24 to get to ".. done", 3:20 to get to "computing newick trees" and 3:50 until all warning are printed out and all is done. I hope this is within the normal range.

**Comment by xrotwang** [comment]
So with some effort I managed to extract the reference lookup such that it can be run for a single sheet. It still takes about 15secs (on my machine), so I'd put it in a separate command such as not to slow down `grambank check`. Output would look like this:
```
$ time grambank sourcelookup original_sheets/HPG_komc1235.tsv ../../glottolog/glottolog
Resolved sources:
17	s_Moye_Kom	Moye, Judith Fonyuy. 2003. Reduplication in Kom: A Morphosyntactic Study. (MA thesis, Université de Yaoundé I; xi+124pp.)
178	s_Shultz_Kom	Shultz, George. 1997. Kom Language Grammar Sketch. Yaoundé: Yaoundé: Summer Institute of Linguistics. 42pp.

Unresolved sources:
6	Moye 1997

Available sources:
hvw:Piron:Bantoide	book	Piron, Pascale 1997
w:ChilverKaberry:Western-Grassfields	book	Chilver, Elizabeth M. and Kaberry, Phyllis M. 1974
typ:Loh:Kom	mastersthesis	Loh, Christopher Njuakom 2001
hvw:Piron:Bantoide:1996	phdthesis	Piron, Pascale 1996
s:Shultz:Kom	book	Shultz, George 1997
phon:Shultz:Kom	misc	Shultz, George 1993
hv:Grollemund:Bantu-Expansion	article	Rebecca Grollemund and Simon Branford and Koen Bostoen and Andrew Meade and Chris Venditti and Mark Pagel 2015
d:Jones:Kom	misc	Jones, Randy 2001
s:Moye:Kom	mastersthesis	Moye, Judith Fonyuy 2003
typ:Kawuldim:Kom	mastersthesis	Kawuldim, Kimbi Paul 2008
s:Bruens:Nkom	article	Bruens, A. 1942/1945
hld:ChilverKaberry:Bamenda-Numerals	incollection	Chilver, Elizabeth M. and Kaberry, Phyllis M. 1966

FAIL

```

**Comment by HedvigS** [comment]
That's great! I was worried I was doing something wrong somehow because of the time, but this is a perfect solution. I'll run cldf to get a list of all errors and then as I go through for specific sheets I'll run this, brilliant. Will sync and reinstall pygrambank now.

**Comment by HedvigS** [comment]
Here's what happens for me now after having reinstalled pygrambank in a new virtual environment:
```

$ grambank sourcelookup /Users/skirgard/Dropbox/Git/Grambank/original_sheets/RSC_waya1268.tsv /Users/skirgard/Dropbox/Git/glottolog
/Users/skirgard/py_venvs/Grambank/lib/python3.8/site-packages/clldutils/clilib.py:173: UserWarning: No module named 'bs4' pygrambank.commands.issues
  warnings.warn('{0} {1}'.format(e, modname))
Traceback (most recent call last):
  File "/Users/skirgard/py_venvs/Grambank/bin/grambank", line 11, in <module>
    load_entry_point('pygrambank', 'console_scripts', 'grambank')()
  File "/Users/skirgard/Dropbox/Git/pygrambank/src/pygrambank/__main__.py", line 36, in main
    return args.main(args) or 0
  File "/Users/skirgard/Dropbox/Git/pygrambank/src/pygrambank/commands/sourcelookup.py", line 37, in run
    run_(args, args.glottolog)
  File "/Users/skirgard/Dropbox/Git/pygrambank/src/pygrambank/commands/sourcelookup.py", line 41, in run_
    sources, unresolved, lgks = refs(args.repos, glottolog, Sheet(args.sheet))
  File "/Users/skirgard/Dropbox/Git/pygrambank/src/pygrambank/cldf.py", line 57, in refs
    bibs.update(api.bib)
  File "/Users/skirgard/py_venvs/Grambank/lib/python3.8/site-packages/clldutils/misc.py", line 195, in __get__
    result = instance.__dict__[self.__name__] = self.fget(instance)
  File "/Users/skirgard/Dropbox/Git/pygrambank/src/pygrambank/api.py", line 33, in bib
    return {e.key: (e.type, e.fields) for e in BibFile(self.repos / 'gb.bib').iterentries()}
  File "/Users/skirgard/Dropbox/Git/pygrambank/src/pygrambank/api.py", line 33, in <dictcomp>
    return {e.key: (e.type, e.fields) for e in BibFile(self.repos / 'gb.bib').iterentries()}
  File "/Users/skirgard/py_venvs/Grambank/lib/python3.8/site-packages/pyglottolog/references/bibfiles.py", line 148, in iterentries
    for k, (t, f) in bibtex.iterentries(filename=self.fname, encoding=self.encoding):
  File "/Users/skirgard/py_venvs/Grambank/lib/python3.8/site-packages/pyglottolog/references/bibtex.py", line 51, in iterentries
    with memorymapped(str(filename)) as source:
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/Users/skirgard/py_venvs/Grambank/lib/python3.8/site-packages/clldutils/path.py", line 27, in memorymapped
    f = Path(filename).open('rb')
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/pathlib.py", line 1213, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/pathlib.py", line 1069, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'gb.bib'
```

I don't know what's going on, trying to problem solve right now.

**Comment by HedvigS** [comment]
And yes, gb.bib is there

`/Users/skirgard/Dropbox/Git/Grambank/gb.bib`

**Comment by chrzyki** [comment]
Heya Hedvig,

you have to be in the `Grambank` directory for this to work (for the command to find `gb.bib`), i.e. in my case:

```
$ pwd
/Users/chrzyki/Repositories/Glottobank/Grambank
```

Then:

```
$ grambank sourcelookup original_sheets/RSC_waya1268.tsv ~/Repositories/glottolog/glottolog

Resolved sources:
168	Pawley2018	Andrew Pawley. 2018. A Short Grammar of Wayan. unpublished grammar sketch.
120	s_Geraghty_Nadroga	Paul Geraghty. 2002. Nadrogā. In John Lynch and Malcolm Ross and Terry Crowley (eds.), The Oceanic Languages, 833-847. Richmond: Richmond: Curzon.
29	wtyp_Biggs_Western-Viti-Levu	Bruce G. Biggs. 1948. The Mba dialects, Western Viti Levu. Journal of the Polynesian Society 57. 68-87.

OK
```

Paths (e.g. Glottolog path for the `sourcelookup` command) are of course subject to change depending on your local setup.

**Comment by HedvigS** [comment]
Ah okay. I had assumed that all paths which needed to be specified would be arguments to the command, okay. Moving to the correct folder then.

**Comment by HedvigS** [comment]
Okay, it almost works now. still getting

```
/Users/skirgard/py_venvs/Grambank/lib/python3.8/site-packages/clldutils/clilib.py:173: UserWarning: No module named 'bs4' pygrambank.commands.issues
  warnings.warn('{0} {1}'.format(e, modname))

```

but I do get the expected output from the command as well

```
Resolved sources:
168	Pawley2018	Andrew Pawley. 2018. A Short Grammar of Wayan. unpublished grammar sketch.
120	s_Geraghty_Nadroga	Paul Geraghty. 2002. Nadrogā. In John Lynch and Malcolm Ross and Terry Crowley (eds.), The Oceanic Languages, 833-847. Richmond: Richmond: Curzon.
29	wtyp_Biggs_Western-Viti-Levu	Bruce G. Biggs. 1948. The Mba dialects, Western Viti Levu. Journal of the Polynesian Society 57. 68-87.

OK

```

**Comment by HedvigS** [comment]
Thanks @chrzyki

**Comment by chrzyki** [comment]
> Okay, it almost works now. still getting
> 
> ```
> /Users/skirgard/py_venvs/Grambank/lib/python3.8/site-packages/clldutils/clilib.py:173: UserWarning: No module named 'bs4' pygrambank.commands.issues
>   warnings.warn('{0} {1}'.format(e, modname))
> ```

This is `pygrambank` telling you that its `issues` command can't be loaded because it requires the `bs4` package. This can be fixed by running `pip install bs4` inside your `pygrambank` virtual environment (i.e. the environment must be sourced). Once you've done this the warning should be gone.

**Comment by HedvigS** [comment]
Yes, I realised that. I just thought I should point that out since I assumed that means that installing bs4 should be added somewhere when all of pygrambank is installed.

**Comment by chrzyki** [comment]
https://github.com/grambank/pygrambank/pull/25 :)

**Comment by HedvigS** [comment]
Is it too tricky to ask that `gb.bib `is located via the first argument to sourcelookup? Because it should always be on up from `original_sheets`

I'll make a note of always being in the grambank folder when running this, it's fine. Just thought I'd check how tricky it'd be so I get a sense.

**Comment by chrzyki** [comment]
You can explicitly specify where your Grambank repository (and hence `gb.bib`) is by using `--repos`:

```
$ grambank --repos /Users/chrzyki/Repositories/Glottobank/Grambank sourcelookup /Users/chrzyki/Repositories/Glottobank/Grambank/original_sheets/RSC_waya1268.tsv /Users/chrzyki/Repositories/glottolog/glottolog
```

This would then work from any location on your file system.

**Comment by HedvigS** [comment]
Cool, I'll do that then. Thanks
