### ISSUE TITLE
New describe command

### ISSUE THREAD

**Issue by xrotwang** [grambank/pygrambank#24]
It may be useful to have a command `grambank describe SHEET`, which
- lists all contributing coders
- gives summary stats on the values
- lists all (author, year, page) triples which can be parsed from `Source`s

basically a tailor-made version of `csvstat` for grambank sheets.

The idea is that this command should be run as final plausibility check on changed sheets - before running `grambank cldf` on the whole repos.

**Comment by xrotwang** [comment]
So here's what I have so far:
```
$ grambank describe original_sheets/SVM_tafi1243.tsv 

Path:
original_sheets/SVM_tafi1243.tsv

Check:

Values:
0	 46
1	 43
2	  4
?	  1
	 94

Sources:
Bobuafor 2013:	 94

Coders:
SVM	Suzanne van der Meer:	 94
ML	Mandy Lorenzen:	 13
```

**Comment by SimonGreenhill** [comment]
looks good. What about including any warnings from `grambank check`?

**Comment by xrotwang** [comment]
That's included (my example above just happened to have none):
```
$ grambank describe original_sheets/CB-PE-AS_yind1248.tsv 

Path:
original_sheets/CB-PE-AS_yind1248.tsv

Check:
CB-PE-AS_yind1248	WARNING	GB117	source given, but no value
CB-PE-AS_yind1248	WARNING	GB117	comment given, but no value

Dimensions:
88 rows
5 columns

Values:
?	 40
0	 33
1	 12
3	  2
	 87

Sources:
Breen 2000:	 98

Coders:
CB	Claire Bowern:	 87
PE	Patience Epps:	 87
AS	Amalia Skilton:	 87
```

**Comment by SimonGreenhill** [comment]
cool!
