### ISSUE TITLE
check breaking?

### ISSUE THREAD

**Issue by HedvigS** [grambank/pygrambank#26]
`check` seems to be breaking in a way I don't understand. I've pulled the latest version of pygrambank and installed it in my virtual python environment. I've looked for hidden files in original_sheets. This happens both with and without report.

```
$ grambank --repos /Users/skirgard/Dropbox/Git/Grambank check --report /Users/skirgard/Dropbox/Git/Grambank/check.tsv
CB-PE-AS_ache1246	WARNING	GB020	value without source
CB-PE-AS_ache1246	WARNING	GB021	value without source
[..]
CB-PE-AS_chem1251	WARNING	GB433	value without source
JV-ML_chey1247	ERROR		missing column Feature_ID
Traceback (most recent call last):
  File "/Users/skirgard/py_venvs/Grambank/bin/grambank", line 11, in <module>
    load_entry_point('pygrambank', 'console_scripts', 'grambank')()
  File "/Users/skirgard/Dropbox/Git/pygrambank/src/pygrambank/__main__.py", line 36, in main
    return args.main(args) or 0
  File "/Users/skirgard/Dropbox/Git/pygrambank/src/pygrambank/commands/check.py", line 36, in run
    n = sheet.check(api, report=report)
  File "/Users/skirgard/Dropbox/Git/pygrambank/src/pygrambank/sheet.py", line 197, in check
    features.add(row['Feature_ID'])
KeyError: 'Feature_ID'
```

What am I doing wrong?

**Comment by SimonGreenhill** [comment]
One of the sheets, probably the one you've just added, doesn't  have a "Feature_ID" column. Probably has "Grambank ID"

**Comment by HedvigS** [comment]
Thanks Simon.

I think it turned out to be [the sheet Robert just fixed this morning.](https://github.com/glottobank/Grambank/commit/1d2bd2ee3ee4166428da29216a748509ff7f61fd#diff-35d5bef31d2f6b601cf8e6aacc1f16c4)

It must have slit in earlier and we didn't notice. Re-running now.

**Comment by HedvigS** [comment]
Yup, that was it.

**Comment by SimonGreenhill** [comment]
BTW: I've been trying to add common errors and fixes here: https://github.com/glottobank/Grambank/tree/master/For_editors

**Comment by HedvigS** [comment]
Oh? Cool. Thanks!

Hey you don't know of some easy way of using Git diff logs to talk to pygrambank so that we can examine only the changes that have been made since master? I.e. not have to grep the output of check for the sheets which are new/changed? Seems like a travis thing but I don't know. Would make it easier when there's 8+ sheets in a PR.

[ Robert does it like this.](https://github.com/grambank/pygrambank/issues/21)
