### ISSUE TITLE
Patrons included in "most up to date sheet"

### ISSUE THREAD

**Issue by HedvigS** [grambank/pygrambank#30]
It seems like pygrambank cldf is excluding the Patron column when generating "Grambank_most_updated_sheet". That seems unfortunate.

**Comment by HedvigS** [comment]
Sorry, not the CLDF command I think. Whichever is rendering "Grambank_most_updated_sheet"

**Comment by xrotwang** [comment]
Ok, needs to be added here https://github.com/grambank/pygrambank/blob/606b3da1bf63a007edeb4f3fde16d0b33052b733/src/pygrambank/commands/new.py#L29-L39

**Comment by HedvigS** [comment]
Great!
