### ISSUE TITLE
pygrambank cldf contributors warning

### ISSUE THREAD

**Issue by HedvigS** [grambank/pygrambank#34]
`pygrambabnk cldf `is giving me the following warnings:

```
WARNING Table without primary key: contributors.csv - This may cause problems with "cldf createdb"
WARNING /Users/skirgard/Dropbox/Git/grambank-cldf/cldf/values.csv:129575 Key `A` not found in table contributors.csv
WARNING /Users/skirgard/Dropbox/Git/grambank-cldf/cldf/values.csv:204050 Key `A` not found in table contributors.csv

```
As far as I know I have the latest version of glottobank/Grambank and contributors there should be up to date and correctly be able to feed into contributors.csv at grambank-cldf. I also pulled glottolog/glottolog, grambank-cldf and grambank.wiki again just to be sure.

I can't pull origin from command line because the authentication with GitHub isn't working, even though I'm using the identical credentials as in GitHub desktop and in the web browser (I double checked). So, I can't provide you logs from the command line of me pulling down the repos. I don't know how to solve that.

I tried looking for "A .*" in Contributed_Datapoints in any sheet, but I had trouble with compiling all the sheets since they appear to differ in text delims. I'm also assuming that "Key `A`" might have nothing to do with the actual letter A occurring in a file name or Contributed_Datapoints.

**Comment by xrotwang** [comment]
To authenticate from the command line you need an access token instead of the password. This can be created from https://github.com/settings/tokens

**Comment by xrotwang** [comment]
See https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token

**Comment by HedvigS** [comment]
Right okay. So when it asks for username and password, that isn't all that's needed. Okay, I'll go get a token.

**Comment by HedvigS** [comment]
Okay, done. I can now pull. As suspected, it was already correctly pulled by GitHub desktop, but nice to have confirmation.

`Already up to date.`

**Comment by xrotwang** [comment]
There seem to be misaligned columns in two sheets:
```
$ csvstat -t -c Contributed_datapoints original_sheets/JY_jamb1236.tsv 
  7. "Contributed_datapoints"

	Type of data:          Text
	Contains null values:  True (excluded from calculations)
	Unique values:         2
	Longest value:         54 characters
	Most common values:    None (194x)
	                       Adjectives, numerals and pronouns can be reduplicated. (1x)

Row count: 195
```
and
```
$ csvstat -t -c Contributed_Datapoints original_sheets/SR_mich1245.tsv 
  7. "Contributed_Datapoints"

	Type of data:          Text
	Contains null values:  True (excluded from calculations)
	Unique values:         2
	Longest value:         57 characters
	Most common values:    None (998x)
	                       A universal quantifier meaning 'every' is not discussed.  (1x)

Row count: 999
```

**Comment by HedvigS** [comment]
Aha, there we go. Shall I go submit a PR or do you wan to?

I did suspect SR_mich1245, but I had several of those kinds of errors because of the varying text delims.

**Comment by xrotwang** [comment]
The other was merged here: https://github.com/glottobank/Grambank/pull/1155
And it seems `grambank describe` was not run, because doing that now gives:
```
Traceback (most recent call last):
  File "/home/forkel/venvs/grambank/bin/grambank", line 11, in <module>
    load_entry_point('pygrambank', 'console_scripts', 'grambank')()
  File "/home/forkel/venvs/grambank/pygrambank/src/pygrambank/__main__.py", line 36, in main
    return args.main(args) or 0
  File "/home/forkel/venvs/grambank/pygrambank/src/pygrambank/commands/describe.py", line 39, in run
    describe(args, sheet)
  File "/home/forkel/venvs/grambank/pygrambank/src/pygrambank/commands/describe.py", line 87, in describe
    print('{}\t{}:\t{}'.format(k, coders_by_id[k], str(v).rjust(3)))
KeyError: 'A'
```

**Comment by HedvigS** [comment]
I did run `describe`, and it didn't come up with check errors which was what I was primarily looking for as I was going through all the files committed. I didn't know what to make of traceback.

**Comment by HedvigS** [comment]
I can even see in my command line log that I ran describe on this particular sheet :)

**Comment by HedvigS** [comment]
Alright, re-running pygrambank cldf now on a branch where I've sorted this and all should be good. Made PR as well.

**Comment by HedvigS** [comment]
And added to my personal pygrambak manual notes that I should make noise if I see something weird in traceback for pygrambank describe.

**Comment by HedvigS** [comment]
`WARNING Table without primary key: contributors.csv - This may cause problems with "cldf createdb"`

still stands by the way. I sorted the other two warnings, but this one remains.

**Comment by HedvigS** [comment]
(Got what I wanted, 2,131 languages in the CLDF-formatted dataset currently. Not going to push to grambank/grambank-cldf obviously, but just wanted to know.)
