### ISSUE TITLE
report invalid coder IDs, rather than raising error

### ISSUE THREAD

**Issue by xrotwang** [grambank/pygrambank#35]
Instead of
```python
Traceback (most recent call last):
  File "/home/forkel/venvs/grambank/bin/grambank", line 11, in <module>
    load_entry_point('pygrambank', 'console_scripts', 'grambank')()
  File "/home/forkel/venvs/grambank/pygrambank/src/pygrambank/__main__.py", line 36, in main
    return args.main(args) or 0
  File "/home/forkel/venvs/grambank/pygrambank/src/pygrambank/commands/describe.py", line 39, in run
    describe(args, sheet)
  File "/home/forkel/venvs/grambank/pygrambank/src/pygrambank/commands/describe.py", line 87, in describe
    print('{}\t{}:\t{}'.format(k, coders_by_id[k], str(v).rjust(3)))
KeyError: 'A'
```
the problem should be reported in a readable way.

**Comment by HedvigS** [comment]
That would be nice, thanks for being thoughtful. For now my notes say "Make noise if there's something in traceback" and that should catch things hopefully in the meantime :)

**Comment by HedvigS** [comment]
To clarify, the reason I was asking `https://github.com/glottobank/Grambank/pull/1181` how to interpret that particular traceback message it was because I hoped that if I know how to read traceback, you don't have to do more work to make the traceback feedback readable.

**Comment by HedvigS** [comment]
@xrotwang wrote

_Ah, ok. You [posted the symptoms of a problem](https://github.com/glottobank/Grambank/pull/1181#issuecomment-774492328), and I posted a [commented](https://github.com/glottobank/Grambank/pull/1181#issuecomment-774936797) [solution](https://github.com/glottobank/Grambank/pull/1181/commits/05fe5328c9b755ad447444dc140194af22e8d593). So whenever you encounter the symptoms again, consider trying the solution from here._

**Comment by HedvigS** [comment]
Yes, I fully understood that. I was asking for help to interpret the message that traceback produced, so that in future I may be able to read it myself more easily.

**Comment by HedvigS** [comment]
The aim was to make your life easier by understanding the output of pygrambank commands myself. That way, issues like this one #35 don't need to be filed because I'd already be competent enough to read the output. Unless you are imagining other users besides me, Christoph and Simon.
