### ISSUE TITLE
conflicts ignore missing values

### ISSUE THREAD

**Issue by HedvigS** [grambank/pygrambank#40]
can `pygrambank conflicts `please ignore conflicts when one value is missing and the other is not? Currently for example, it reports a conflict for GB042 and acha1250 because CB-PE-AS_acha1250 has a missing value (due to fixhg) and SD_acha1250 has a value.

**Comment by xrotwang** [comment]
fixed now

**Comment by HedvigS** [comment]
Super, thanks!
