### ISSUE TITLE
running cldf on grambank

### ISSUE THREAD

**Issue by HedvigS** [grambank/pygrambank#42]
Hi. Sorry I couldn't find the information about this, but I know we discussed it. I want to run something like pygrambank cldf on glottobank/grambank in order to asses the amount of gained datapoints since the dump late last year. I'm not pushing to grambank/grambank-cldf. The command cldf is no longer part of pygrambank. What should I do?

**Comment by xrotwang** [comment]
Here's the relevant issue: https://github.com/grambank/pygrambank/issues/33

**Comment by xrotwang** [comment]
`grambank cldf` has been replaced with `cldfbench makecldf` - to be run in glottobank/grambank-cldf.

**Comment by HedvigS** [comment]
Ah right, I was looking in pycldf. Sorry. 

I'll start keeping notes on these things in my general pygrambank notes, I'm apparently not good at finding info by searching the different reposes.

**Comment by xrotwang** [comment]
The cldfbench version is also not pushed yet.

**Comment by HedvigS** [comment]
Ok. I'm not sure I understand what that means. the cldfbench version of grambank is not pushed to grambank/grambank-cldf? It shouldn't be, right?

I'm tinkering with cldfbench now.

**Comment by xrotwang** [comment]
The release instructions are not updated yet, see https://github.com/glottobank/grambank-cldf/blob/master/RELEASING.md

**Comment by xrotwang** [comment]
So you need to checkout master in the `raw/Grambank` submodule, and update it, running `git submodule update --remote`.

**Comment by HedvigS** [comment]
Ok. I don't understand what `raw/grambank` is really or what the expected arguments of `makecldf` are (in particular what is expected at `dataset `or `entry-point`.

**Comment by xrotwang** [comment]
Run `cldfbench makecldf cldfbench_grambank.py`.

**Comment by HedvigS** [comment]
oh? ok.

**Comment by xrotwang** [comment]
`raw/Grambank` is the point where `glottobank/Grambank` is "mounted" as git submodule.

**Comment by HedvigS** [comment]
didn't work, I'm guessing because it isn't getting the paths to glottolog etc.

`'Config /Users/skirgard/Library/Application Support/cldf/catalog.ini has no entry for glottolog'
`

**Comment by HedvigS** [comment]
I haven't used git submodules before, I didn't know that we were doing things that required them.

**Comment by xrotwang** [comment]
See https://github.com/grambank/pygrambank/issues/33

**Comment by xrotwang** [comment]
Regarding Glottolog: You can pass the path to a clone of `glottolog/glottolog` as `--glottolog ...`.

**Comment by xrotwang** [comment]
Alternatively, you can manage the glottolog clone via cldfbench, see https://github.com/cldf/cldfbench/#catalogs

**Comment by HedvigS** [comment]
Right.
I'm sorry, I'm just finding this a bit difficult to piece together information from many different places. I saw from the help file on makecldf that indeed the paths were needed and I tried to trial and error that, but I hadn't gotten that to work yet and then you told me to run` cldfbench makecldf cldfbench_grambank.py .` so I just did, not understanding why that would work but then again.. I'm not following several things here.

**Comment by HedvigS** [comment]
`pygrambank cldf` worked by me feeding in the paths to the wiki, glottobank/grambank etc etc and that was all fine. I'm just now trying to wrap my head around this about git submodules etc.

**Comment by xrotwang** [comment]
To initialize the submodules, run
```
git submodule init
git submodule update
```

**Comment by xrotwang** [comment]
Then, you basically have a clone of wiki and Grambank in `raw/`.

**Comment by HedvigS** [comment]
I saw that I should do that [here](cldfbench makecldf cldfbench_grambank.py.). Now I'm trying to understand where. I'm sorry, I know I'm very slow with this.

**Comment by HedvigS** [comment]
I'd prefer just feeding` cldfbench makecldf `with the paths to the clones I already have if that's possible.

**Comment by xrotwang** [comment]
That's not possible. The `cldfbench makecldf` command is defined in the `cldfbench` package and doesn't allow arbitrary additional arguments.

**Comment by HedvigS** [comment]
Right okay.

**Comment by HedvigS** [comment]
So, where should I run

```
git submodule init
git submodule update
```

?

**Comment by xrotwang** [comment]
in `grambank-cldf`.

**Comment by xrotwang** [comment]
Note that this will clone `glottobank/Grambank`. That's 1.5 GB. If you don't have good internet, just copy your clone of glottobank/Grambank to `raw/Grambank`.

**Comment by xrotwang** [comment]
Whenever any of my `RELEASING` docs mention shell commands, they are assumed to be executed in the directory where that `RELEASING` doc resides.

**Comment by HedvigS** [comment]
Okay, that's running now.

Right, okay. I didn't make that assumption.

**Comment by HedvigS** [comment]
Okay, Git submodules done. It looks like makecldf is running now.

**Comment by HedvigS** [comment]
Alright okay, everything ran. We have 9005 new non-? datappoints. That may not seem like a lot, and that's mainly because we've spent so much effort on revision work lately.
