### ISSUE TITLE
describe and check giving different output

### ISSUE THREAD

**Issue by HedvigS** [grambank/pygrambank#48]
When I run pygrambank` check` on the entire dir of original_sheets, it doesn't pop up a warning for CB-PE-AS_wapi1253. However, when I run `describe `on that particular sheet, I get the following check warnings:

```
CB-PE-AS_wapi1253	WARNING	L11	GB046	source given, but no value
CB-PE-AS_wapi1253	WARNING	L11	GB046	comment given, but no value
CB-PE-AS_wapi1253	WARNING	L15	GB051	source given, but no value
CB-PE-AS_wapi1253	WARNING	L15	GB051	comment given, but no value
CB-PE-AS_wapi1253	WARNING	L20	GB059	source given, but no value
CB-PE-AS_wapi1253	WARNING	L20	GB059	comment given, but no value
CB-PE-AS_wapi1253	WARNING	L26	GB089	source given, but no value
CB-PE-AS_wapi1253	WARNING	L26	GB089	comment given, but no value
CB-PE-AS_wapi1253	WARNING	L31	GB113	source given, but no value
CB-PE-AS_wapi1253	WARNING	L31	GB113	comment given, but no value
CB-PE-AS_wapi1253	WARNING	L34	GB117	source given, but no value
CB-PE-AS_wapi1253	WARNING	L34	GB117	comment given, but no value
CB-PE-AS_wapi1253	WARNING	L46	GB149	source given, but no value
CB-PE-AS_wapi1253	WARNING	L46	GB149	comment given, but no value
CB-PE-AS_wapi1253	WARNING	L78	GB409	source given, but no value
CB-PE-AS_wapi1253	WARNING	L78	GB409	comment given, but no value
CB-PE-AS_wapi1253	WARNING	L84	GB070	source given, but no value
CB-PE-AS_wapi1253	WARNING	L84	GB070	comment given, but no value
```

**Comment by xrotwang** [comment]
It may be that check only operates on selected sheets.

Hedvig Skirgård ***@***.***> schrieb am Mo., 23. Aug. 2021,
10:26:

**Comment by HedvigS** [comment]
Check is giving me a table of errors in lots of other sheets. Here's an excerpt:

sheet | selected | level | feature | message |  
-- | -- | -- | -- | -- | --
CB-PE-AS_aghu1254 | True | WARNING | L11 | GB046 | source given, but no value
CB-PE-AS_aghu1254 | True | WARNING | L11 | GB046 | comment given, but no value
CB-PE-AS_aghu1254 | True | WARNING | L15 | GB051 | source given, but no value
CB-PE-AS_aghu1254 | True | WARNING | L15 | GB051 | comment given, but no value
CB-PE-AS_aghu1254 | True | WARNING | L20 | GB059 | source given, but no value
CB-PE-AS_aghu1254 | True | WARNING | L20 | GB059 | comment given, but no value
CB-PE-AS_aghu1254 | True | WARNING | L25 | GB089 | source given, but no value
CB-PE-AS_aghu1254 | True | WARNING | L25 | GB089 | comment given, but no value
CB-PE-AS_aghu1254 | True | WARNING | L26 | GB090 | source given, but no value
CB-PE-AS_aghu1254 | True | WARNING | L26 | GB090 | comment given, but no value
CB-PE-AS_aghu1254 | True | WARNING | L33 | GB113 | source given, but no value
CB-PE-AS_aghu1254 | True | WARNING | L33 | GB113 | comment given, but no value
CB-PE-AS_aghu1254 | True | WARNING | L49 | GB149 | source given, but no value
CB-PE-AS_aghu1254 | True | WARNING | L49 | GB149 | comment given, but no value
CB-PE-AS_aghu1254 | True | WARNING | L77 | GB408 | source given, but no value
CB-PE-AS_aghu1254 | True | WARNING | L77 | GB408 | comment given, but no value
CB-PE-AS_aghu1254 | True | WARNING | L84 | GB519 | source given, but no value
CB-PE-AS_aghu1254 | True | WARNING | L84 | GB519 | comment given, but no value
CB-PE-AS_aghu1254 | True | WARNING | L87 | GB070 | source given, but no value
CB-PE-AS_aghu1254 | True | WARNING | L87 | GB070 | comment given, but no value
CB-PE-AS_ajyi1238 | True | WARNING | L7 | GB035 | source given, but no value
CB-PE-AS_ajyi1238 | True | WARNING | L7 | GB035 | comment given, but no value
CB-PE-AS_ajyi1238 | True | WARNING | L10 | GB046 | source given, but no value
CB-PE-AS_ajyi1238 | True | WARNING | L10 | GB046 | comment given, but no value

**Comment by xrotwang** [comment]
`grambank check` - without any arguments - checks all **selected** sheets. `CB-PE-AS_wapi*` is not one of these. To verify that `check` does the same as the check in `describe`, see:
```
$ grambank check --filename original_sheets/CB-PE-AS_wapi1253.tsv 
CB-PE-AS_wapi1253	WARNING	11	GB046	source given, but no value
CB-PE-AS_wapi1253	WARNING	11	GB046	comment given, but no value
CB-PE-AS_wapi1253	WARNING	15	GB051	source given, but no value
CB-PE-AS_wapi1253	WARNING	15	GB051	comment given, but no value
CB-PE-AS_wapi1253	WARNING	20	GB059	source given, but no value
CB-PE-AS_wapi1253	WARNING	20	GB059	comment given, but no value
CB-PE-AS_wapi1253	WARNING	26	GB089	source given, but no value
CB-PE-AS_wapi1253	WARNING	26	GB089	comment given, but no value
CB-PE-AS_wapi1253	WARNING	31	GB113	source given, but no value
CB-PE-AS_wapi1253	WARNING	31	GB113	comment given, but no value
CB-PE-AS_wapi1253	WARNING	34	GB117	source given, but no value
CB-PE-AS_wapi1253	WARNING	34	GB117	comment given, but no value
CB-PE-AS_wapi1253	WARNING	46	GB149	source given, but no value
CB-PE-AS_wapi1253	WARNING	46	GB149	comment given, but no value
CB-PE-AS_wapi1253	WARNING	78	GB409	source given, but no value
CB-PE-AS_wapi1253	WARNING	78	GB409	comment given, but no value
CB-PE-AS_wapi1253	WARNING	84	GB070	source given, but no value
CB-PE-AS_wapi1253	WARNING	84	GB070	comment given, but no value
```

**Comment by HedvigS** [comment]
Ah, that explains it. Thanks.
