### ISSUE TITLE
false positive sourcelookup match

### ISSUE THREAD

**Issue by HedvigS** [grambank/pygrambank#62]
Strings that refer to personal correspondence seem to sometimes be mistakenly matched to sources in hh.bib or gb.bib. For example, for nenn1238 "Evans, Nicholas (p.c. 2018)" is matched to:

[Evans, Nicholas. 2018. Mission unexpected. In Green, Jennifer and Myfany Turpin and Felicity Meakins (eds.), Understanding Linguistic Fieldwork, 13–16. London: Routledge.](https://glottolog.org/resource/reference/id/571139)

Maybe we should make a general rule that if "p.c." occurs in the source string sourcelookup doesn't go on looking for a match?

**Comment by xrotwang** [comment]
just removing the year from p.c. sources would work too.

**Comment by HedvigS** [comment]
Whatever works I'm happy with.

I'm also submitting a PR soon to glottobank/grambank for standardising the p.c. string.

**Comment by HedvigS** [comment]
I hope you don't mean remove the year in the sheets? They're useful.

**Comment by xrotwang** [comment]
I did mean "remove the year in the sheets". I can sort-of see why one might think this is useful. But since "p.c." is so informal anyway, what good does this extra info do?

**Comment by HedvigS** [comment]
Okay good.

It can help the persons involved track down their conversations.

**Comment by xrotwang** [comment]
Ok, then some fiddling in https://github.com/grambank/pygrambank/blob/201c68e55e69b5c1720af607a84509f7a130de8c/src/pygrambank/srctok.py#L140-L146 is needed.

**Comment by xrotwang** [comment]
It looks like you could just start the ref with "p.c.":
```python
>>> list(iter_ayps('Nicholas Evans (p.c. 2018)'))
[('Nicholas Evans (p.c', '2018', None, None)]
>>> list(iter_ayps('p.c. Nicholas Evans (2018)'))
[]
```

**Comment by HedvigS** [comment]
> It looks like you could just start the ref with "p.c.":
> 
> ```python
> >>> list(iter_ayps('Nicholas Evans (p.c. 2018)'))
> [('Nicholas Evans (p.c', '2018', None, None)]
> >>> list(iter_ayps('p.c. Nicholas Evans (2018)'))
> []
> ```

I've looked at other instances of sources with "p.c." and a year noted (see table below), and while they vary in whether the "p.c." occurs before or after the year, I've found none where it is the first item.

I would like to suggest that we do not have a principle of putting "p.c." first because I think that'll not naturally occur to everyone to do every time but instead follow what is already in the database and add an exception to our sourcelook script such that if it finds "p.c." it doesn't go looking for a match. If we don't merge in [this branch](https://github.com/glottobank/Grambank/pull/2037) we should add additional patterns to that exception, such as "pers. comm.", "pers comm" etc.

filename | Source
-- | --
DP_chuu1238 | Hyun-Jong Hahm (p.c. 2018)
DP_chuu1238 | Myjolynne Marie Kim (p.c. 2018)
DS_idii1243 | Schokkin, Dineke p.c., 2017
GB_nese1235 | Crowley (2006: 78), Lana Grelyn Takau (2016:294), Lana Grelyn Takau (p.c. 2018)
GB_nese1235 | Crowley (2006), Lana Grelyn Takau (p.c. 2018)
GB_nese1235 | Lana Grelyn Takau (p.c. 2018)
GB_nese1235 | Crowley (2006: 51), Lana Grelyn Takau (p.c. 2018)
HH_laal1242 | Florian Lionnet (p.c. 2017)
HS_avat1244 | Defina and van Putten (p.c. 2014)
HS_bamb1266 | Möller, Mirjam (2014 p.c.)
HS_bang1363 | Hantgan, Abbie (p.c. 2014)
HS_bena1262 | Bernander, Rasmus (p.c. 2014)
HS_bidy1244 | Segerer, G (2013 p.c.)
HS_chac1249 | Floyd, Simeon (2014 p.c.)
HS_esan1238 | Rolle, Nicholas (p.c. 2014)
HS_finn1318 | Lehtinen, Jyri (p.c. 2014)
HS_goro1270 | Harvey, Andrew (2014 p.c. )
HS_guro1248 | Kuznetsova, Olga (p.c. 2013)
HS_juho1239 | Pratchett, James Lee (2014 p.c.)
HS_kaby1243 | Mettouchi, Amina (p.c. 2014)
HS_kagf1238 | Paterson, Becky (2014 p.c.)
HS_kera1248 | Segerer, G (2013 p.c.)
HS_loma1260 | Mishchenko, Daria (p.c. 2013)
HS_maas1239 | Bah, Amadu Sajoh (p.c. 2013) Native speaker and Chief editor of Peeral.com
HS_maas1239 | Apel, Viktoria (p.c. 2014)
HS_mand1423 | Bernander, Rasmus (p.c. 2014)
HS_mand1436 | Creissels, Denis (p.c. 2013)
HS_mann1248 | Khachaturyan, Maria (p.c. 2013)
HS_mbug1242 | Wilhelmsen (2014 p.c.)
HS_mmen1238 | Möller, Mirjam (2014 p.c.)
HS_nige1253 | Bah, Amadu Sajoh (p.c. 2013) Native speaker and Chief editor of Peeral.com
HS_nige1253 | Apel, Viktoria (p.c. 2014)
HS_nkor1239 | Ebikudo, Ebitare (p.c. 2014)
HS_nort2775 | Roulon-Doko, Paulette (p.c. 2013)
HS_nucl1347 | Diagne, Anna Marie (p.c. 2013)
HS_pula1262 | Bah, Amadu Sajoh (p.c. 2013) Native speaker and Chief editor of Peeral.com
HS_pula1262 | Apel, Viktoria (p.c. 2014)
HS_pula1263 | Bah, Amadu Sajoh (p.c. 2013) Native speaker and Chief editor of Peeral.com
HS_pula1263 | Apel, Viktoria (p.c. 2014)
HS_sekp1241 | Delalorm, Cephas (2014 p.c.)
HS_sini1242 | Diagne, Anna Marie (p.c. 2013)
HS_soni1259 | Diagne, Anna Marie (p.c. 2013)
HS_swed1254 | Skirgård, Hedvig (p.c. 2014)
HS_tigo1236 | Doris Richter. (p.c. 2013)
HS_toma1245 | Mishchenko, Daria (p.c. 2013)
HS_ukaa1243 | Salffner (p.c. 2014)
HS_wann1242 | Nikitina, Tatiana (p.c. 2013)
HS_yaou1238 | Elizaveta Kushnir (2014, p.c.)
IC-TM_russ1263 | Rizaew, Julia (p.c., 2018)
IC-TM_russ1263 | Trokhymenko, Laura (p.c., 2018)
JC_laoo1244 | Enfield 2007:p.c.
JC-HS_stan1293 | Collins, Jeremy (p.c. 2014)
JLA-MDU_hano1246 | Bogiri (2011:56-57), Duhamel (p.c.)
JLE_bila1255 | Constance Kutsch Lojenga, p.c. 2016
JLE_hadi1240 | Suzanne van der Meer, p.c. 2017
JLE_kamm1249 | Jakob Lesage (p.c. 2021)
JLE_kamm1249 | Jakob Lesage, p.c. 2020
JLE_kamm1249 | Jakob Lesage (p.c. 2020)
JLE_onaa1245 | Luis-Miguel Rojas Berscia, p.c. 2015
JLE_yaka1272 | Thomas, Jacqueline (2015 p.c.)
JS_waru1265 | Jane Simpson (p.c. 2016)
MD-GR-RSI_siro1249 | Jacqueline van Kleef and Sjaak van Kleef p.c. 27/7/2011
MM_turk1304 | Hoey, Elliott (p.c. 2014)
MM_udih1248 | Oskolskaya (p.c. 2017)
NB_vera1241 | Schnell p.c. 2017
NE_nenn1238 | Evans, Nicholas (p.c. 2018)
NH_bagi1246 | Peggy Jacob (p.c. 2016)
NH_bagi1246 | Stevenson (1969:32-33), Peggy Jacob (p.c. 2016)
NH_bagi1246 | Stevenson (1969:47,80,103-105), Peggy Jacob (p.c. 2016)
NH_bash1264 | Gisbert Fanselow (p.c. 2017)
NH_bash1264 | Alexandr Savelyev p.c. 2020)
NH_chec1245 | Zarina Molochieva p.c. 2015
NH_chuv1255 | Savelev, Alexandr (p.c. 2016)
NH_chuv1255 | Savelev, Alexandr (p.c. 2017)
NH_huih1238 | Sofia Oskolskaya (p.c. 2017)
NH_manc1252 | Malchukov (p.c.2018)
NH_nana1257 | Sofia Oskolskaya (p.c. 2018)
NH_negi1245 | Sofia Oskolskaya (p.c. 2017)
NH_nort2697 | Orkhan Mehraliev (p.c. 2017)
NH_nucl1301 | Gisbert Fanselow (p.c. 2017)
NH_shor1247 | Gisbert Fanselow (p.c. 2017)
NH_tata1255 | Gisbert Fanselow (p.c. 2017)
NH_tata1255 | Savelev (p.c. 2018)
NH_tuvi1240 | Savelyev (p.c. 2018)
NH_ukra1253 | Neshcheret p.c. 2016
NH_ukra1253 | Pugh (1999:125-129), Neshcheret p.c. 2016
NH_ulch1241 | Sofia Oskolskaya (p.c. 2017)
NH_yaku1245 | Gisbert Fanselow (p.c. 2017)
NH_yaku1245 | Andrej L. Malchukov (p.c. 2018)
NP_boun1245 | Rumsey 2018 p.c.
NP_kili1267 | Gunter Senft (2018 p.c.)
NP_kili1267 | Lawton 1993:87, Gunter Senft (2018 p.c.)
NP_leme1238 | Schnell 2018 (p.c.)
NP_mang1401 | Mary Walworth (p.c.) 2018
NP_uraa1244 | Donohue & Donohue 2016:183-184, Mark Donohue & Naomi Peck (p.c.)
NP_wiru1244 | Yihan Chen, Rebecca Dixon and Caroline Hendy p.c. (2018)
NP_wiru1244 | Caroline Hendy p.c. (2018)
OK_hupd1244 | Epps (2008:292,p.c. 2009)
OK_kwaz1243 | Hein van der Voort, p.c. 2010
OK_maco1239 | Rosés Labrada (2015, p.c. 2015)
OK_maco1239 | Rosés Labrada (p.c. 2015)
OK_maco1239 | Rosés Labrada (p.c.2015)
OK_maco1239 | Rosés Labrada (2015:313, p.c. 2015)
OK_maco1239 | Rosés Labrada (2015:299-313, p.c. 2015)
OK_maco1239 | Rosés Labrada (2015:318, p.c. 2015)
OK_maco1239 | Rosés Labrada (2015:193, 315, p.c. 2015)
OK_maco1239 | Rosés Labrada (2015:369, p.c. 2015)
OK_maco1239 | Rosés Labrada (2015:217, p.c. 2015)
OK_maco1239 | Rosés Labrada (2015:64, p.c. 2015)
OK_maco1239 | Rosés Labrada (2015:166, 283, p.c.)
OK_maco1239 | Rosés Labrada (2015:215, p.c. 2015)
OK_maco1239 | Rosés Labrada (2015:528, p.c. 2015)
OK_maco1239 | Rosés Labrada (2015:385, p.c. 2015)
RHE_brib1243 | Adela López Vargas (p.c. 2015)
RHE_brib1243 | Constenla (1998:129ff, 53, 86) Adela López Vargas (p.c. 2015)
RHE_brib1243 | Adela Lopez Vargas (p.c. 2015)
RHE_male1297 | Constenla (1998), p.c. Alfredo Acosta Blanco
RHE_tojo1241 | Antonio Magaña Macías (p.c., 2016)
RK_lule1254 | UiT 2018: http://gtweb.uit.no/korp/?mode=smj#?cqp=[]&search=word\|g%C3%A5&page=0. Olle Kejonen, p.c. 2016
RSC_akab1249 | Comrie 2018 (p.c.)
RSC_akab1249 | Zamponi 2018 (p.c.)
RSC_akab1249 | Comrie & Zamponi 2018 (p.c.)
RSC_balu1257 | Schokkin p.c. 2018
RSC_haru1245 | Comrie 2019 (p.c.)
RSC_moro1289 | Arka 2020 (p.c.)
RSC_natu1246 | Næss 2018 (p.c.)
RSC_nucl1487 | Pawley 2018 (p.c.)
RSC_nucl1487 | Geraghty 2018 (p.c.)
RSC_nucl1487 | Pawley 2020 (p.c.)
RSC_taul1251 | Meng 2018 (p.c.)
RSC_tiko1237 | Pawley 2018 (p.c.)
RSC_tora1259 | Parkinson 2019 (p.c.)
RSC_tora1259 | Parkinson 2018 (p.c.)
RSC_waya1268 | Pawley (p.c. 2018)
RSC_waya1268 | Geraghty (p.c. 2018)
RSC_waya1268 | Pawley 2018 (p.c.)
RSC_waya1268 | Pawley 2020 (p.c.) Pawley 2018:99
SPI-JW_wara1294 | Döhler (p.c. 2017)
SPI-JW_wara1294 | Döhler (2016:405-407), Döhler (p.c. 2017)
SR_jeju1234 | Kim (p.c. 2020)
SVM_kamb1316 | Treis 2014:p.c.
SVM_kamb1316 | Treis (2008) 2014:264, p.c.
SVM_nama1264 | Hagman 1977:p.c.
SY_matu1261 | Danielle Barth (p.c. 2016)
TWI_khar1287 | Peterson p.c. 2015
TY_bali1278 | Ratih Oktarini 2015 (p.c.)
TY_bali1278 | Ratih Ratih Oktarini (p.c. 2015)
YGA_rapa1245 | Walworth p.c. 2018

**Comment by xrotwang** [comment]
What about this: `Rosés Labrada (2015:528, p.c. 2015)`. If the code "doesn't go looking for a match" here, it'll miss one reference.

**Comment by HedvigS** [comment]
Since this isn't the correct way of formatting references I'm going through now and preparing a branch to resolve these. I've found 9 coding sheets with problems of this kind

**Comment by HedvigS** [comment]
voila :) https://github.com/glottobank/Grambank/pull/2038

**Comment by HedvigS** [comment]
So, sourcelookup should run on each item between semi colons or the only item in the field

**Comment by HedvigS** [comment]
This issue was resolved in that the pygrambank code was updated, but the source linked in Grambank 1.0 is still faulty. Are we addressing that or do we wait until next release?

**Comment by xrotwang** [comment]
Wait until the next release.

**Comment by HedvigS** [comment]
Okay.
