### ISSUE TITLE
threshold of at least 25 features with comment

### ISSUE THREAD

**Issue by HedvigS** [grambank/pygrambank#63]
We want to encourage people to leave comments in coding sheets.

I've discussed with coders and we think that if pygrambank describe gives a warning if less than 25 active features have something (anything) in the comment field that would be a good incentive. There are of course exceptions, such as "the sheet is only filled in for 12 features" or "there really isn't a lot to say", and if that's the case we'd merge them in any way despite the warning. But, everyone in the International node thought this would be a good idea to just check when things are submitted anew.

I'd filter these warnings out when making the to do list for warnings to fix in existing sheets, no point in caring about these for old sheets I think.

**Comment by xrotwang** [comment]
Wouldn't that be rather a candidate for a pre-submission checklist? As it is now, submitted sheets can be quickly merged if there are no warnings. This would introduce a round of reviewer-submitter feedback for some of these sheets.

**Comment by HedvigS** [comment]
True. The idea is that that round of reviewer-submittet feedback is worth it.

**Comment by xrotwang** [comment]
If you are the default reviewer then that's fine with me.

**Comment by HedvigS** [comment]
Cool!

**Comment by HedvigS** [comment]
Honestly most new sheets getting submitted should easily clear this bar.

**Comment by HedvigS** [comment]
Could you help me with modifying the relevant python? I'm not sure how to best organise it.

**Comment by xrotwang** [comment]
here's the relevant commit https://github.com/grambank/pygrambank/commit/cb6bbe3bd0ff5fdc8790df9c91eb7e67fe48d6bd
