### ISSUE TITLE
odd behaviour with sourcelookup SR_acha1250

### ISSUE THREAD

**Issue by HedvigS** [grambank/pygrambank#64]
when I makecldf with cldfbench inside the grambank-cldf repos, all goes well and I get sourcelookup fails printed to me on the command line.

`cldfbench makecldf cldfbench_grambank.py  --glottolog  /Users/skirgard/Nextcloud/Git/glottolog --glottolog-version v4.5
`

One of these sourcelookup fails is
`('SD_acha1250', 'acha1250') 1`

However, I can't find this in the source col in this sheet (SR_acha1250). When I run sourcelookup individually on this sheet I get some things I haven't seen before:
```

(Grambank) dlmp133190:grambank-cldf skirgard$ grambank --repos /Users/skirgard/Nextcloud/Git/Grambank sourcelookup /Users/skirgard/Nextcloud/Git/glottolog /Users/skirgard/Nextcloud/Git/Grambank/original_sheets/SR_acha1250.tsv 
/Users/skirgard/py_venvs/Grambank/lib/python3.8/site-packages/clldutils/clilib.py:233: UserWarning: No module named 'fuzzywuzzy' pygrambank.commands.wiki
  warnings.warn('{0} {1}'.format(e, modname))
Resolved sources:
127	g_Wilson_Achagua	Peter J. Wilson. 1992. Una Descripción Preliminar de la Gramática del Achagua (Arawak). Riberalta, Bolivia: Instituto Lingüística del Verano. vi+184pp.
1	g_Melendez_Achagua	Meléndez Lozano, Miguel Angel. 1998. La lengua Achagua: Estudio Gramátical. (Lenguas Aborígenes de Colombia: Descripciones, 11.) Bogotá: CESO-CCELA, Universidad de los Andes. 202pp.

OK
```

What is fuzzywuzzy? Why is a source failing lookup in cldfbench, but not in individually with sourcelookup?

**Comment by HedvigS** [comment]
I've now installed fuzzywuzzy and python-Levenshtein separately, so that's all good. I guess that had something to do with the fix for #63 maybe? or #62 ?

**Comment by HedvigS** [comment]
[Right, it's this commit. Got it.](https://github.com/grambank/pygrambank/commit/17ae77774d399554717096b5f5fc239b9ac4362d)

**Comment by xrotwang** [comment]
Can't confirm. Here's what I get with current master:
```
('Li', '2015', 'sout2730') 1
('Donohue', '2001', 'siaw1243') 1
('Hyman & Comrie', '1981', 'nucl1417') 1
('Torrence', '2005', 'nucl1347') 1
('Li', '2015', 'nort2724') 1
('Aikhenvald', '2000', 'natu1246') 1
('Bertoglia', '1983', 'cabe1245') 1
('Adelaar and Himmelmann', '2005', 'taro1264') 2
('Lynch', '1998', 'warr1255') 3
('Palmer', '2007', 'urua1242') 3
('Mazaudon', '2008', 'tsha1245') 3
('Smith texts', 'sanb1242') 5
('Payne', '2012', 'enap1235') 5
('Mangulu', '2002', 'ngom1268') 6
('Alves', '2001', 'jehh1245') 6
```

What does `git status` in `raw/Grambank` say?

**Comment by HedvigS** [comment]
Weird. I'm up to date with with grambank-cldf, grambank and pygrambank.

```
(Grambank) dlmp133190:grambank-cldf skirgard$ git status
On branch master
Your branch is up to date with 'origin/master'.

(Grambank) dlmp133190:Git skirgard$ cd grambank-cldf/raw/
(Grambank) dlmp133190:raw skirgard$ git status
On branch master
Your branch is up to date with 'origin/master'.

(Grambank) dlmp133190:Git skirgard$ cd grambank
(Grambank) dlmp133190:grambank skirgard$ git status
On branch master
Your branch is up to date with 'origin/master'.

(Grambank) dlmp133190:pygrambank skirgard$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean

```

**Comment by HedvigS** [comment]
Is it something with cldfbench in some way?

**Comment by xrotwang** [comment]
Maybe you have multiple clones of `glottobank/Grambank` in `raw`? The one defined as submodule `Grambank`, with capital `G`, see https://github.com/glottobank/grambank-cldf/blob/master/.gitmodules

**Comment by HedvigS** [comment]
Maybe, I'm not sure how this is meant to work. I just clone the grambank-cldf repos and then I run
```
git submodule init
git submodule update
```

**Comment by HedvigS** [comment]
[I can see the relevant line here.](https://github.com/glottobank/Grambank/blob/b32afb9393e1415fda564c757d29d7965b0b3f99/original_sheets/SR_acha1250.tsv#L30)

**Comment by HedvigS** [comment]
I'm copying over the grambank dir now from the glottobank/Grambank repos to grambank/grambank/raw. I'm a bit confused.

**Comment by HedvigS** [comment]
I haven't used git submodules so much before, but I didn't think I needed to do that?

**Comment by xrotwang** [comment]
What does `la raw/` look like in your clone of `grambank-cldf`? Here's mine:
```shell
$ la raw/
glottolog-cldf
Grambank
grambank.wiki
README.md
wals
```

**Comment by HedvigS** [comment]
I'll test that in a moment, I'm running cldfbench now on the manually copied over submodule

**Comment by xrotwang** [comment]
The `Grambank` and `grambank.wiki` entries are the ones pulled in as git submodules. But they behave just like regular clones, so you can `cd` in there, checkout branches, work on PRs, etc. So on my machine, `grambank-cldf/raw/Grambank` is the **only** clone of `glottobank/Grambank` that I have.

**Comment by HedvigS** [comment]
Yeah, so I thought that `git submodule update` was taking care of the syncing there, but it appears it's not somehow.

**Comment by HedvigS** [comment]
I have two clones of "grambank", one just plain where all my other reposes live and then one as a submodule within grambank-cldf

**Comment by HedvigS** [comment]
Is that not a valid move then, two have essentially 2 clones?

**Comment by xrotwang** [comment]
> Yeah, so I thought that `git submodule update` was taking care of the syncing there, but it appears it's not somehow.

1. The `--remote` option is the key here, so `git submodule update --remote` should be closer to what you were expecting.
2. [.gitmodules](https://github.com/glottobank/grambank-cldf/blob/d3def0074498f1bd7ff9c63faf874e6bfbd847a1/.gitmodules#L7) specifies a particular branch for the `Grambank` repos. To override that, you'd need to navigate to `raw/Grambank` and checkout `master` instead.

**Comment by xrotwang** [comment]
> Is that not a valid move then, two have essentially 2 clones?

It is a valid setup - but one that you always need to be aware of.

**Comment by HedvigS** [comment]
> > Yeah, so I thought that `git submodule update` was taking care of the syncing there, but it appears it's not somehow.
> 
> 1. The `--remote` option is the key here, so `git submodule update --remote` should be closer to what you were expecting.
> 2. [.gitmodules](https://github.com/glottobank/grambank-cldf/blob/d3def0074498f1bd7ff9c63faf874e6bfbd847a1/.gitmodules#L7) specifies a particular branch for the `Grambank` repos. To override that, you'd need to navigate to `raw/Grambank` and checkout `master` instead.

riiight ok.

**Comment by HedvigS** [comment]
I'll update my notes for how this works then.

**Comment by HedvigS** [comment]
So I ran `git submodule update --remote` inside grambank-cldf/raw/grambank.

and then:

```
(Grambank) dlmp133190:grambank skirgard$ git status
HEAD detached at b32afb93
nothing to commit, working tree clean
```

**Comment by HedvigS** [comment]
Riight.. so. the git submodule doesn't automatically pull master? What does it do if I go `git submodule update --remote`

**Comment by xrotwang** [comment]
It updates to the HEAD in the specified branch.

**Comment by xrotwang** [comment]
There is no global idea of **most up to date** in a git repository. That's only per branch. The fact that often one branch has a special role is pure convention.

**Comment by HedvigS** [comment]
Right... so I assumed, apparently wrong, that the default for the git submodule was the master branch. I've never changed branch there as far as I know, so I didn't even consider it not being on master.

**Comment by xrotwang** [comment]
I linked to it above: https://github.com/grambank/pygrambank/issues/64#issuecomment-1049629526

**Comment by HedvigS** [comment]
Yeah, I just got confused why I was even ever on a non-master branch. I'll figure it out, thanks for the help and patience Robert :)!
