### ISSUE TITLE
additional rules for check

### ISSUE THREAD

**Issue by HedvigS** [grambank/pygrambank#67]
We would like to add these rules to the check flow:

- GB408, GB409 and GB410 can't all be 0
- GB131, GB132 and GB133 can't all be 0
- GB026, GB303, GB320, GB166, GB197, GB129, GB285, GB336, GB260, GB165 and GB319 should not be coded 1 without a comment

**Comment by HedvigS** [comment]
- GB309 can't be 0 if GB083, GB084, GB121 and GB521 are all 0

**Comment by HedvigS** [comment]
- if GB333, GB334, GB3325 and GB336 are all 0, then there needs to be a comment for all of them.

**Comment by HedvigS** [comment]
> ERROR GB309 can't be 0 if GB083, GB084, GB121 and GB521 are all 0

Need to find out what's going on here.

**Comment by johenglisch** [comment]
Just for reference: A link to the relevant comment in the PR I'm about to merge.

https://github.com/glottobank/Grambank/pull/2268#issuecomment-1219183277

**Comment by HedvigS** [comment]
@johenglisch when #79 is merged, does that mean all in this issue is addressed and it can be closed?
