### ISSUE TITLE
Why are these sheets being flagged as empty when they're not?

### ISSUE THREAD

**Issue by SimonGreenhill** [grambank/pygrambank#80]
* ERROR: empty sheet ../original_sheets/JG_anga1290.tsv
* ERROR: empty sheet ../original_sheets/CB-PE-AS_buna1275.tsv
* ERROR: empty sheet ../original_sheets/CB-PE-AS_chem1251.tsv
* ERROR: empty sheet ../original_sheets/MD-GR-RSI_kand1301.tsv
* ERROR: empty sheet ../original_sheets/CB-PE-AS_sout2969.tsv
* ERROR: empty sheet ../original_sheets/CB-PE-AS_utee1244.tsv

**Comment by HedvigS** [comment]
I think it's because of various errors.

For example, for JG_anga1290.tsv the column is called "b0Feature_ID" instead of "Feature_ID"

**Comment by HedvigS** [comment]
[I'm fixing some of them here now.](https://github.com/glottobank/Grambank/tree/fixing-errors-SJG-comment-at-pygrambank)

**Comment by HedvigS** [comment]
CB-PE-AS_buna1275 has all missing sources.  It's already in our to do list for fixing.

**Comment by HedvigS** [comment]
Jep, same for all of them except JG_anga1290. They've all got all missing info for sources and they are in our to do list.
