### ISSUE TITLE
markdown file with rules of check and sourcelookup spelled out

### ISSUE THREAD

**Issue by HedvigS** [grambank/pygrambank#85]
Could we please have a plan language markdown file somewhere on this repos with the rules that pygrambank `check `and `sourcelookup ` checks the coding sheets for?

It'd be handy to show coders and collaborators.

**Comment by xrotwang** [comment]
`sourcelookup` tries to find a source by "Lastname YEAR" among all sources marked up for the given language in Glottolog's `hh.bib`. For `check`, do you mean the dependency checks?

**Comment by xrotwang** [comment]
I think the dependency checks are pretty transparent in https://github.com/grambank/pygrambank/pull/83/files#diff-257071e9dbb65e2ee98600c6a23085db4d11463ca6102d4e2faa142a158ed38e
Copying that info into a separate file would seem to be exactly the kind of info that gets out of sync.

**Comment by HedvigS** [comment]
Thank you.

I meant for all the possible warnings, including invalid values, what exact conditions the bibentry to source need to satisfy.

I need something not for me (person who can read python) but for other people in this project who cannot read python.

**Comment by HedvigS** [comment]
I can get started if you want and then maybe @johenglisch and @xrotwang can adjust where needed?

**Comment by xrotwang** [comment]
Yes, maybe that would make it easier to see what kind of document you'd like to see. From my point of view the major thing is that people know what ERROR or WARNING mean once/if they get them.

**Comment by HedvigS** [comment]
Okay, I've made a start [here](https://github.com/grambank/grambank/wiki/Automatic-quality-checks). I'd be gratefyl for edits and additions ;)

**Comment by HedvigS** [comment]
Could you help me and add to the list of rules, in particular the dependencies and "no comment on rare features"?

**Comment by xrotwang** [comment]
But aren't the error messages in these cases pretty clear? Would you expect coders to check their sheets "manually" first - if we run the authoritative set of checks upon submission anyway?

**Comment by HedvigS** [comment]
I'm sorry, I haven't been clear.

It would be helpful to me, coders and collaborators if in addition to the error messages that happen in PRs we have an overview of what we're currently checking for. They don't need to manually check for these before submission, you're right we have scripts for that, but to have a summary is useful in communication and in training.

We also have collaborators who are building datasets similar to grambank separately, and I'd like to show them the kinds of principles and tools we use and I think a a summary page would be useful for that.
