### ISSUE TITLE
new dependency rule for pygrambank

### ISSUE THREAD

**Issue by HedvigS** [grambank/pygrambank#88]
GB155 can't be 1 and GB113 0 with no comments on both features

**Comment by johenglisch** [comment]
Hm, is this rule satisfied if there is a comment on any of the features?

    if GB155 == 1 and GB113 == 0:
        require_comment(GB155 or GB113)

Or do both need comments?

    if GB155 == 1 and GB113 == 0:
        require_comment(GB155)
        require_comment(GB113)

**Comment by HedvigS** [comment]
Both please.
