### ISSUE TITLE
cldf creation Coders col

### ISSUE THREAD

**Issue by HedvigS** [grambank/pygrambank#89]
Information about Coders only needs to occur in the CLDF ValueTable, it should not occur in the Language Table. The column should be called "Coders" and should be built on info in the raw coding sheets filename combined with the content in the col "[C|c]ontributed_[D|datapoint].

**Comment by HedvigS** [comment]
As discussed [here](https://github.com/glottobank/grambank-cldf/issues/122)

**Comment by johenglisch** [comment]
So, the `Coders` column already exists and is being populated in the ValueTable:

https://github.com/grambank/pygrambank/blob/80aefa612a8082b974a2d89897c60a80f6b06917/src/pygrambank/cldf.py#L199-L209

So, basically, you just want me to throw out the `Coders` column from the language table?

**Comment by HedvigS** [comment]
Yes, I think we should have this information in one place only and that it makes more sense tied to each data-point rather than to a language as a whole. Alternatively, if we do want to keep it it should list all coders (both in fn and for each row). Right now it doesn't list enough coders.

**Comment by HedvigS** [comment]
And, just to double check: coders in the values table does include both the info from the sheet and row. I'm reading that right?

**Comment by johenglisch** [comment]
Yes

https://github.com/grambank/pygrambank/blob/80aefa612a8082b974a2d89897c60a80f6b06917/src/pygrambank/cldf.py#L171-L172

**Comment by HedvigS** [comment]
Excellent :)!
