### ISSUE TITLE
Tackle source look-up code

### ISSUE THREAD

**Issue by johenglisch** [grambank/pygrambank#99]
I've been putting this off for a while but I think it's time I tackle that source look-up code (as much as it scares me)…

Some observations:

 * Apparently batch lookup using `grambank sourcelookup glottolog sheet1 sheet2 sheet3 ...` works *most of the time* except when it doesn't…  Don't know why…
 * I caught the `Unresolved sources` output 'lying' a few times…
 * afaict you can't just reference a source using a bibkey – it *has* to be Author Year…
   (correct me if I'm wrong)
 * The program does not understand what an `Online Tuvan dictionary (tyvan.ru)` is.
 * Infuriatingly, it *does* unterstand what a `Sakha online dictionary` is.
 * In general, I have trouble understanding the code… (<_<)'

But before that, are PRs #97 and #98 good for merge?

**Comment by xrotwang** [comment]
I can relate to this :) Starting with tests (see https://github.com/grambank/pygrambank/blob/master/tests/test_srctok.py and https://github.com/grambank/pygrambank/blob/master/tests/glottolog/references/bibtex/hh.bib) might be the best way to ease into this topic.
